project_id = "vtdfogroujomnczqrxrs"

[functions.create-checkout]
verify_jwt = false

[functions.delete-member]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.update-member]
verify_jwt = false

[functions.resend-credentials]
verify_jwt = false
